import { useState } from 'react'
import './PromptInspector.css'

function CollapsibleSection({ label, defaultOpen = false, children }) {
  const [open, setOpen] = useState(defaultOpen)

  return (
    <div className="pi-section">
      <button className="pi-toggle" onClick={() => setOpen(!open)}>
        <span className={`pi-arrow ${open ? 'open' : ''}`}>&#9654;</span>
        <span className="pi-section-label">{label}</span>
      </button>
      {open && <div className="pi-section-content">{children}</div>}
    </div>
  )
}

/**
 * Formats the promptSent array into a single string
 * exactly as it was sent to the API.
 */
function formatInput(promptSent) {
  if (!promptSent || !Array.isArray(promptSent)) return null

  return promptSent.map((msg) => {
    return `[${msg.role.toUpperCase()}]\n${msg.content}`
  }).join('\n\n' + '─'.repeat(60) + '\n\n')
}

export default function PromptInspector({ debug, onClose }) {
  if (!debug || debug === 'setup') {
    return (
      <div className="pi-backdrop" onClick={onClose}>
        <div className="pi-modal" onClick={(e) => e.stopPropagation()}>
          <div className="pi-header">
            <h2>Prompt Inspector</h2>
            <button className="pi-close" onClick={onClose}>&times;</button>
          </div>
          <div className="pi-body">
            <p className="pi-note">This message was not generated by the AI.</p>
          </div>
        </div>
      </div>
    )
  }

  const rawInput = formatInput(debug.promptSent)
  const rawOutput = debug.rawResponse || null

  return (
    <div className="pi-backdrop" onClick={onClose}>
      <div className="pi-modal" onClick={(e) => e.stopPropagation()}>
        <div className="pi-header">
          <h2>Prompt Inspector</h2>
          {debug.model && (
            <span className="pi-meta">
              {debug.model}
              {debug.usage && ` · ${debug.usage.prompt_tokens}→${debug.usage.completion_tokens} tokens`}
            </span>
          )}
          <button className="pi-close" onClick={onClose}>&times;</button>
        </div>
        <div className="pi-body">
          {debug.error && !rawInput && (
            <pre className="pi-code pi-error">{debug.error}</pre>
          )}

          {rawInput && (
            <CollapsibleSection label="Input (sent to AI)" defaultOpen={false}>
              <pre className="pi-code">{rawInput}</pre>
            </CollapsibleSection>
          )}

          {rawOutput && (
            <CollapsibleSection label="Output (received from AI)" defaultOpen={true}>
              <pre className="pi-code">{rawOutput}</pre>
            </CollapsibleSection>
          )}
        </div>
      </div>
    </div>
  )
}
