import './PromptInspector.css'

export default function PromptInspector({ debug, onClose }) {
  if (debug === 'setup') {
    return (
      <div className="prompt-inspector-backdrop" onClick={onClose}>
        <div className="prompt-inspector" onClick={(e) => e.stopPropagation()}>
          <div className="pi-header">
            <h2>Prompt Inspector</h2>
            <button className="pi-close" onClick={onClose}>&times;</button>
          </div>
          <div className="pi-body">
            <div className="pi-section">
              <div className="pi-section-label">Source</div>
              <div className="pi-setup-badge">Setup</div>
              <p className="pi-note">
                This is the opening scene. It was not generated by the AI — it is a
                hardcoded introduction that sets the stage for the story.
              </p>
            </div>
          </div>
        </div>
      </div>
    )
  }

  const hasReasoning = debug?.reasoning
  const hasError = debug?.error
  const hasPrompt = debug?.promptSent

  return (
    <div className="prompt-inspector-backdrop" onClick={onClose}>
      <div className="prompt-inspector" onClick={(e) => e.stopPropagation()}>
        <div className="pi-header">
          <h2>Prompt Inspector</h2>
          <button className="pi-close" onClick={onClose}>&times;</button>
        </div>
        <div className="pi-body">
          {hasError && !hasPrompt && (
            <div className="pi-section">
              <div className="pi-section-label">Error</div>
              <pre className="pi-code pi-error">{debug.error}</pre>
            </div>
          )}

          {hasPrompt && (
            <div className="pi-section">
              <div className="pi-section-label">Prompt Sent to AI</div>
              <div className="pi-messages">
                {debug.promptSent.map((msg, i) => (
                  <div key={i} className={`pi-msg pi-msg-${msg.role}`}>
                    <span className="pi-msg-role">{msg.role}</span>
                    <pre className="pi-msg-content">{msg.content}</pre>
                  </div>
                ))}
              </div>
            </div>
          )}

          {hasReasoning && (
            <div className="pi-section">
              <div className="pi-section-label">AI Reasoning / Thoughts</div>
              <pre className="pi-code pi-reasoning">{debug.reasoning}</pre>
            </div>
          )}

          {hasPrompt && (
            <div className="pi-section">
              <div className="pi-section-label">AI Response</div>
              <pre className="pi-code">{debug.responseContent}</pre>
            </div>
          )}

          {debug?.model && (
            <div className="pi-section pi-meta">
              <span>Model: {debug.model}</span>
              {debug.usage && (
                <span>Tokens: {debug.usage.prompt_tokens} prompt / {debug.usage.completion_tokens} completion</span>
              )}
              {debug.finishReason && <span>Finish: {debug.finishReason}</span>}
            </div>
          )}
        </div>
      </div>
    </div>
  )
}
